### ISSUE TITLE
fiologparser and fio2gnuplot reports error "too many values to unpack (expected 4)"

### ISSUE THREAD

**Issue by MichelePardini** [axboe/fio#1014]
Hi
I am using fio-3.20-38-g14060, I noticed that all logs (bw, clat, slat) have now 5 columns, for instance

_:::/fio/fsx/256/logs # head 256_iomix_1_bw_bw.log
35, 7622, 0, 262144, 0
35, 7629, 0, 262144, 0
36, 7762, 0, 262144, 0
36, 7833, 0, 262144, 0
36, 7861, 0, 262144, 0
37, 7883, 0, 262144, 0
37, 7957, 0, 262144, 0
38, 7977, 0, 262144, 0
38, 8025, 0, 262144, 0
38, 8094, 0, 262144, 0_

All parsers are failing with error 

_:::>/fio/tools/fiologparser.py 256_iomix_1_bw_bw.log_

_Traceback (most recent call last):
  File "/fio/tools/fiologparser.py", line 214, in <module>
    series.append(TimeSeries(ctx, fn))
  File "/fio/tools/fiologparser.py", line 163, in __init__
    self.read_data(fn)
  File "/fio/tools/fiologparser.py", line 169, in read_data
    (time, value, foo, bar) = line.rstrip('\r\n').rsplit(', ')
**ValueError: too many values to unpack (expected 4)**_

I am not using these logs often but looking around I believe they used to have 4 colums. Is it something expected or am I doing something wrong? 
thanks

**Comment by vincentkfu** [comment]
There was a logging format change and the log parsers were not updated. More details are at https://github.com/axboe/fio/issues/928
