### ISSUE TITLE
fio with --verify=crc32c will be failed with "fio: file hash not empty on exit" on aarch64

### ISSUE THREAD

**Issue by yizhanglinux** [axboe/fio#1239]
**Description of the bug:**
fio with --verify=crc32c will be failed with "fio: file hash not empty on exit" on aarch64

**Environment**: 
5.13-rc4 aarch64

**fio version**: 
fio-3.27-22-gafa3

**Reproduction steps**
```
$ fio --output=/root/fio_perf --name=verify --rw=randwrite --verify=crc32c --filename=/root/testfile
fio: pid=1084, got signal=4
fio: file hash not empty on exit
```

**Comment by sitsofe** [comment]
Hi @yizhanglinux,

Signal 4 is an illegal instruction. Which ARM platform are you running on and did you compile your fio binary on the same (or lesser) platform than the one you're running your fio binary on?

**Comment by yizhanglinux** [comment]
> Hi @yizhanglinux,
> 
> Signal 4 is an illegal instruction. Which ARM platform are you running on and did you compile your fio binary on the same (or lesser) platform than the one you're running your fio binary on?

Here is the CPU Vendor/Model info: FUJITSU/A64FX

Yes, I just tried on another the same platform and it still can be reproduced.

**Comment by sandeen** [comment]
Hi @sitsofe -

Apparently this has been seen on fio-3.19 as well, so whatever it is it seems to not be a recent regression.

@yizhanglinux - it might be interesting to get the src.rpm and do rpmbuild --rebuild and install the result, i.e. compile it on the same platform as you are testing, just to see how that behaves.

-Eric

**Comment by sitsofe** [comment]
@sandeen Good to know. My first guess is that the binary has an optimisation not supported by that platform if it was built _without_` --disable-native`. My next guess is that the platform somehow doesn't support the neon instructions used to accelerate ARM builds (see https://github.com/axboe/fio/blob/master/crc/crc32c-arm64.c ) but somehow passes the probing...

**Comment by sitsofe** [comment]
@yizhanglinux
- Does the error go away if you compile fio with the --disable-native option
- Does the problem reproduce with the following command lines
```
fio --name=test --filename=/tmp/test --size=64k --do_verify=0 --verify=crc32c
```

```
fio --name=test --filename=/tmp/test --size=64k --do_verify=0 --verify=crc32
```

(note the lack of a "c" on the second line)

**Comment by axboe** [comment]
@sitsofe the sigill is due to the assert triggering, it's just a side effect of that, not the actual issue.

**Comment by yizhanglinux** [comment]
> Hi @sitsofe -
> 
> Apparently this has been seen on fio-3.19 as well, so whatever it is it seems to not be a recent regression.
> 
> @yizhanglinux - it might be interesting to get the src.rpm and do rpmbuild --rebuild and install the result, i.e. compile it on the same platform as you are testing, just to see how that behaves.
> 
> -Eric

Same behavior after rebuild the fio src rpm

**Comment by yizhanglinux** [comment]
> @yizhanglinux
> 
> * Does the error go away if you compile fio with the --disable-native option

The error still exists.

> * Does the problem reproduce with the following command lines
> 
> ```
> fio --name=test --filename=/tmp/test --size=64k --do_verify=0 --verify=crc32c
> ```
> 
> ```
> fio --name=test --filename=/tmp/test --size=64k --do_verify=0 --verify=crc32
> ```
> 
> (note the lack of a "c" on the second line)

Reproduced another error with above cmd
```
# fio --name=test --filename=/tmp/test --size=64k --do_verify=0 --verify=crc32c
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.27
Starting 1 process
verify: bad magic header e035, wanted acca at file /tmp/test offset 0, length 4096 (requested block: offset=0, length=4096)
fio: pid=60183, err=84/file:io_u.c:2102, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character

test: (groupid=0, jobs=1): err=84 (file:io_u.c:2102, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character): pid=60183: Mon Jun 21 22:16:13 2021
  read: IOPS=1000, BW=4000KiB/s (4096kB/s)(4096B/1msec)
    clat (nsec): min=15320, max=15320, avg=15320.00, stdev= 0.00
     lat (nsec): min=16700, max=16700, avg=16700.00, stdev= 0.00
    clat percentiles (nsec):
     |  1.00th=[15296],  5.00th=[15296], 10.00th=[15296], 20.00th=[15296],
     | 30.00th=[15296], 40.00th=[15296], 50.00th=[15296], 60.00th=[15296],
     | 70.00th=[15296], 80.00th=[15296], 90.00th=[15296], 95.00th=[15296],
     | 99.00th=[15296], 99.50th=[15296], 99.90th=[15296], 99.95th=[15296],
     | 99.99th=[15296]
  lat (usec)   : 20=100.00%
  cpu          : usr=0.00%, sys=0.00%, ctx=0, majf=0, minf=18
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=50.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=4000KiB/s (4096kB/s), 4000KiB/s-4000KiB/s (4096kB/s-4096kB/s), io=4096B (4096B), run=1-1msec
```

```
# fio --name=test --filename=/tmp/test --size=64k --do_verify=0 --verify=crc32
test: (g=0): rw=read, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=psync, iodepth=1
fio-3.27
Starting 1 process
verify: bad magic header e035, wanted acca at file /tmp/test offset 0, length 4096 (requested block: offset=0, length=4096)
fio: pid=60211, err=84/file:io_u.c:2102, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character

test: (groupid=0, jobs=1): err=84 (file:io_u.c:2102, func=io_u_sync_complete, error=Invalid or incomplete multibyte or wide character): pid=60211: Mon Jun 21 22:17:16 2021
  read: IOPS=1000, BW=4000KiB/s (4096kB/s)(4096B/1msec)
    clat (nsec): min=15700, max=15700, avg=15700.00, stdev= 0.00
     lat (nsec): min=17060, max=17060, avg=17060.00, stdev= 0.00
    clat percentiles (nsec):
     |  1.00th=[15680],  5.00th=[15680], 10.00th=[15680], 20.00th=[15680],
     | 30.00th=[15680], 40.00th=[15680], 50.00th=[15680], 60.00th=[15680],
     | 70.00th=[15680], 80.00th=[15680], 90.00th=[15680], 95.00th=[15680],
     | 99.00th=[15680], 99.50th=[15680], 99.90th=[15680], 99.95th=[15680],
     | 99.99th=[15680]
  lat (usec)   : 20=100.00%
  cpu          : usr=0.00%, sys=0.00%, ctx=0, majf=0, minf=18
  IO depths    : 1=100.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=50.0%, 4=50.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=1,0,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
   READ: bw=4000KiB/s (4096kB/s), 4000KiB/s-4000KiB/s (4096kB/s-4096kB/s), io=4096B (4096B), run=1-1msec
```

**Comment by sitsofe** [comment]
The more recent outputs are to be expected. What size is `/root/testfile` ? Is it basically the size of the free space on the filesystem?

**Comment by yizhanglinux** [comment]
No, it's the size my specified.

```
# fio --output=/root/fio_perf --output-format=terse --terse-version=4 --group_reporting=1 --name=verify --rw=randwrite --direct=1 --ioengine=libaio --bs=4k --iodepth=16 --verify=crc32c --size=950m --filename=/root/testfile
fio: pid=104620, got signal=4
fio: file hash not empty on exit
# du -sh /root/testfile 
950M	/root/testfile
```

**Comment by sitsofe** [comment]
@yizhanglinux Does the problem still occur with the following:
```
fio --minimal --name=verify4 --rw=randwrite --verify=crc32c --filename=/root/testfile 
```

```
fio --minimal --name=verify5 --rw=write --verify=crc32c --filename=/root/testfile 
```

```
fio --minimal --name=verify6 --rw=randwrite --verify=crc32c --filename=/root/testfile --size=50M
```

**Comment by yizhanglinux** [comment]
@sitsofe 
all failed, let me know if you need more info for it.

> @yizhanglinux Does the problem still occur with the following:
> 
> ```
> fio --minimal --name=verify4 --rw=randwrite --verify=crc32c --filename=/root/testfile 
> ```

```
# ./fio --minimal --name=verify4 --rw=randwrite --verify=crc32c --filename=/root/testfile 
fio: pid=23667, got signal=4
3;fio-3.27-57-gfaff8;verify4;0;0;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;0.000000%;0.000000%;0;0;0;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;nan%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;dm-0;0;62;0;0;0;10;10;3.31%;slaves;0;62;0;0;0;2;2;3.31%;nvme0n1;0;62;0;0;0;2;2;3.31%
fio: file hash not empty on exit
```

> 
> ```
> fio --minimal --name=verify5 --rw=write --verify=crc32c --filename=/root/testfile 
> ```
> 

```
# ./fio --minimal --name=verify5 --rw=write --verify=crc32c --filename=/root/testfile 
fio: pid=23735, got signal=4
3;fio-3.27-57-gfaff8;verify5;0;0;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;0.000000%;0.000000%;0;0;0;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;nan%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;dm-0;0;67;0;0;0;0;0;2.48%;slaves;0;67;0;0;0;3;3;2.48%;nvme0n1;0;67;0;0;0;3;3;2.48%
fio: file hash not empty on exit

```

> ```
> fio --minimal --name=verify6 --rw=randwrite --verify=crc32c --filename=/root/testfile --size=50M
> ```

```
# ./fio --minimal --name=verify6 --rw=randwrite --verify=crc32c --filename=/root/testfile --size=50M
fio: pid=23573, got signal=4
3;fio-3.27-57-gfaff8;verify6;0;0;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;0;0;0;0;0;0;0.000000;0.000000;0;0;0.000000;0.000000;1.000000%=0;5.000000%=0;10.000000%=0;20.000000%=0;30.000000%=0;40.000000%=0;50.000000%=0;60.000000%=0;70.000000%=0;80.000000%=0;90.000000%=0;95.000000%=0;99.000000%=0;99.500000%=0;99.900000%=0;99.950000%=0;99.990000%=0;0%=0;0%=0;0%=0;0;0;0.000000;0.000000;0;0;0.000000%;0.000000;0.000000;0.000000%;0.000000%;0;0;0;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;0.0%;nan%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;0.00%;dm-0;12;105;0;0;0;0;0;5.56%;slaves;12;105;0;0;3;3;7;5.56%;nvme0n1;12;105;0;0;3;3;7;5.56%
fio: file hash not empty on exit

```

**Comment by yizhanglinux** [comment]
Any update for this issue, feel free to let me know if you need any debug testing for it. :)

Thanks
Yi

**Comment by sandeen** [comment]
FWIW, there is a [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=1962050) where even simply:

# fio --crctest=crc32c
Illegal instruction (core dumped)

crashes.

**Comment by sitsofe** [comment]
The Fedora bug shows a clear backtrace for `fio --crctest=crc32c`:
```
(gdb) thread apply all bt

Thread 1 (Thread 0xfffff7fef010 (LWP 9814) "fio"):
#0  crc32c_arm64 (data=0xffffefa0b018 "\213\202\360zj[\354\017Q\220\030\016\365MU\037\n\222\232Y\262\"\347\016AR.\002\211\267I\024HJ%\367ٵK\nI\251\300\231({T\034)\225\223\276\204B\265\b\245\362=\315\006I\263\035
T>U\340\201\002v\034ʧ\340\234%Й\021\371\024\267_\224k&\006\237bz\001\227\235\211\023S\314߮\365\262>\n\212y\262\317\356\376Q\005\061O1\235\004\330x\031\346\251\r\354g\314C\t<\265\216(\206\203\276\036\247\326sj)\27
4\270\027\324\372\372AKb\263\005Z_\325\352K\313\\\006뫭\315\376\243\033\b}5\300\003\251\r\261\003\257\206\271\005՟\314\024հ_\335\035\021\270\001\032vA\343s\023;\034"..., data@entry=0xffffefa0b010 "^\024\374(D\17
7\343\003\213\202\360zj[\354\017Q\220\030\016\365MU\037\n\222\232Y\262\"\347\016AR.\002\211\267I\024HJ%\367ٵK\nI\251\300\231({T\034)\225\223\276\204B\265\b\245\362=\315\006I\263\035T>U\340\201\002v\034ʧ\340\234%
Й\021\371\024\267_\224k&\006\237bz\001\227\235\211\023S\314߮\365\262>\n\212y\262\317\356\376Q\005\061O1\235\004\330x\031\346\251\r\354g\314C\t<\265\216(\206\203\276\036\247\326sj)\274\270\027\324\372\372AKb\263\0
05Z_\325\352K\313\\\006뫭\315\376\243\033\b}5\300\003\251\r\261\003\257\206\271\005՟\314\024հ_\335\035\021\270\001"..., length=length@entry=131072) at crc/crc32c-arm64.c:64
#1  0x0000aaaaaaabbd6c in fio_crc32c (len=131072, buf=0xffffefa0b010 "^\024\374(D\177\343\003\213\202\360zj[\354\017Q\220\030\016\365MU\037\n\222\232Y\262\"\347\016AR.\002\211\267I\024HJ%\367ٵK\nI\251\300\231({T
\034)\225\223\276\204B\265\b\245\362=\315\006I\263\035T>U\340\201\002v\034ʧ\340\234%Й\021\371\024\267_\224k&\006\237bz\001\227\235\211\023S\314߮\365\262>\n\212y\262\317\356\376Q\005\061O1\235\004\330x\031\346\251
\r\354g\314C\t<\265\216(\206\203\276\036\247\326sj)\274\270\027\324\372\372AKb\263\005Z_\325\352K\313\\\006뫭\315\376\243\033\b}5\300\003\251\r\261\003\257\206\271\005՟\314\024հ_\335\035\021\270\001"...) at crc/
../crc/crc32c.h:53
#2  t_crc32c (t=0xaaaaaab70260 <t.lto_priv+96>, buf=0xffffefa0b010, size=131072) at crc/test.c:93
#3  0x0000aaaaaaac333c in fio_crctest (type=<optimized out>) at crc/test.c:410
#4  0x0000aaaaaaacbde4 in parse_cmd_line (argc=argc@entry=2, argv=argv@entry=0xfffffffff598, client_type=client_type@entry=1) at /usr/src/debug/fio-3.26-2.fc34.aarch64/init.c:2863
#5  0x0000aaaaaaaccd74 in parse_options (argv=0xfffffffff598, argc=2) at /usr/src/debug/fio-3.26-2.fc34.aarch64/init.c:2992
#6  parse_options (argc=2, argv=0xfffffffff598) at /usr/src/debug/fio-3.26-2.fc34.aarch64/init.c:2982
#7  0x0000aaaaaaab90a0 in main (argc=2, argv=0xfffffffff598, envp=<optimized out>) at /usr/src/debug/fio-3.26-2.fc34.aarch64/fio.c:42
```

`crc/crc32c-arm64.c:64` is the following:
```
 60                 /* Merge crc0 and crc1 into crc2 
 61                    crc1 multiply by K2
 62                    crc0 multiply by K1 */
 63 
 64                 t1 = (uint64_t)vmull_p64(crc1, k2);
 65                 t0 = (uint64_t)vmull_p64(crc0, k1);
```

So it appears that the `vmull_p64` instruction is the one not supported. Searching the web turns up https://github.com/google/crc32c/pull/6#issuecomment-328713398 which points out that pmull is optional for armv8 cores so we will have to runtime detect if it present. Could someone try the following patch and see if it helps:
```diff
diff --git a/os/os-linux.h b/os/os-linux.h
index f7137abe..e6cb2e98 100644
--- a/os/os-linux.h
+++ b/os/os-linux.h
@@ -21,6 +21,9 @@
 
 #ifdef ARCH_HAVE_CRC_CRYPTO
 #include <sys/auxv.h>
+#ifndef HWCAP_PMULL
+#define HWCAP_PMULL             (1 << 4)
+#endif /* HWCAP_PMULL */
 #ifndef HWCAP_CRC32
 #define HWCAP_CRC32             (1 << 7)
 #endif /* HWCAP_CRC32 */
@@ -427,7 +430,8 @@ static inline bool os_cpu_has(cpu_features feature)
 #ifdef ARCH_HAVE_CRC_CRYPTO
 	case CPU_ARM64_CRC32C:
 		hwcap = getauxval(AT_HWCAP);
-		have_feature = (hwcap & HWCAP_CRC32) != 0;
+		have_feature = (hwcap & (HWCAP_PMULL | HWCAP_CRC32)) ==
+			       (HWCAP_PMULL | HWCAP_CRC32);
 		break;
 #endif
 	default:
```

**Comment by yizhanglinux** [comment]
@sitsofe 
Sorry for the delay as I missed this update, after apply the change, it works now.
Feel free to add:
Tested-by: Yi Zhang <yi.zhang@redhat.com>

```
# ./fio  --group_reporting=1 --name=verify --rw=randwrite --direct=1 --ioengine=libaio --bs=4k --iodepth=16 --verify=crc32c --size=950m --filename=/root/testfile
verify: (g=0): rw=randwrite, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=libaio, iodepth=16
fio-3.28-123-ged7f-dirty
Starting 1 process
Jobs: 1 (f=1): [V(1)][100.0%][r=64.8MiB/s][r=16.6k IOPS][eta 00m:00s]                  
verify: (groupid=0, jobs=1): err= 0: pid=99697: Mon Nov 29 21:36:35 2021
  read: IOPS=16.5k, BW=64.6MiB/s (67.8MB/s)(950MiB/14699msec)
    slat (usec): min=15, max=3471, avg=20.02, stdev= 8.61
    clat (usec): min=45, max=4405, avg=909.79, stdev=47.78
     lat (usec): min=64, max=4435, avg=930.35, stdev=48.52
    clat percentiles (usec):
     |  1.00th=[  791],  5.00th=[  840], 10.00th=[  865], 20.00th=[  889],
     | 30.00th=[  898], 40.00th=[  906], 50.00th=[  914], 60.00th=[  922],
     | 70.00th=[  930], 80.00th=[  938], 90.00th=[  947], 95.00th=[  971],
     | 99.00th=[ 1012], 99.50th=[ 1037], 99.90th=[ 1057], 99.95th=[ 1074],
     | 99.99th=[ 1139]
  write: IOPS=14.6k, BW=57.1MiB/s (59.9MB/s)(950MiB/16630msec); 0 zone resets
    slat (usec): min=49, max=3139, avg=59.58, stdev= 9.86
    clat (usec): min=32, max=4120, avg=1031.32, stdev=39.32
     lat (usec): min=93, max=4172, avg=1091.47, stdev=40.61
    clat percentiles (usec):
     |  1.00th=[ 1020],  5.00th=[ 1020], 10.00th=[ 1020], 20.00th=[ 1020],
     | 30.00th=[ 1020], 40.00th=[ 1020], 50.00th=[ 1020], 60.00th=[ 1029],
     | 70.00th=[ 1037], 80.00th=[ 1045], 90.00th=[ 1045], 95.00th=[ 1057],
     | 99.00th=[ 1090], 99.50th=[ 1090], 99.90th=[ 1123], 99.95th=[ 1172],
     | 99.99th=[ 3195]
   bw (  KiB/s): min=13720, max=58824, per=97.82%, avg=57223.53, stdev=7689.08, samples=34
   iops        : min= 3430, max=14706, avg=14305.88, stdev=1922.27, samples=34
  lat (usec)   : 50=0.01%, 100=0.01%, 250=0.01%, 500=0.01%, 750=0.04%
  lat (usec)   : 1000=49.26%
  lat (msec)   : 2=50.68%, 4=0.01%, 10=0.01%
  cpu          : usr=66.50%, sys=31.68%, ctx=15550, majf=0, minf=841
  IO depths    : 1=0.1%, 2=0.1%, 4=0.1%, 8=0.1%, 16=100.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=243200,243200,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
   READ: bw=64.6MiB/s (67.8MB/s), 64.6MiB/s-64.6MiB/s (67.8MB/s-67.8MB/s), io=950MiB (996MB), run=14699-14699msec
  WRITE: bw=57.1MiB/s (59.9MB/s), 57.1MiB/s-57.1MiB/s (59.9MB/s-59.9MB/s), io=950MiB (996MB), run=16630-16630msec

Disk stats (read/write):
    dm-0: ios=239917/243204, merge=0/0, ticks=16210/6020, in_queue=22230, util=99.79%, aggrios=243200/243208, aggrmerge=0/0, aggrticks=17695/6360, aggrin_queue=24054, aggrutil=99.36%
```
