### ISSUE TITLE
fio segfaults when number of jobs exceeds maximum jobs

### ISSUE THREAD

**Issue by sitsofe** [axboe/fio#318]
Description of the problem
fio segfaults in an a mutex assertion when the number of jobs exceeds the maximum number of jobs.

Steps to reproduce:
1. Run
```
./fio --max-jobs=4 --ioengine=null --numjobs=5 --name=maxjobs --size=10M
```

Expected results:
Error message and for fio to exit cleanly.

Actual results:
```
$ ./fio --max-jobs=4 --ioengine=null --numjobs=5 --name=nulltest --rw=randrw --size=10M 
error: maximum number of jobs (4) reached.
Segmentation fault (core dumped)
```

Version information:
Ubuntu 16.04
fio commit 349cdc89ffebb8f3a9cf3ff5be6a9934b94f1b05 (latest at time of writing)

Additional information:
Looking at things in gdb when using `--thread` shows the following:
```
Thread 1 "fio" received signal SIGSEGV, Segmentation fault.
fio_mutex_up (mutex=0x0) at mutex.c:231
231		assert(mutex->magic == FIO_MUTEX_MAGIC);
(gdb) thread apply all bt

Thread 4 (Thread 0x7fffed75c700 (LWP 19105)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000448fd9 in fio_mutex_down (mutex=0x7ffff7faa000) at mutex.c:219
#2  0x00000000004618bd in thread_main (data=<optimised out>) at backend.c:1501
#3  0x00007ffff72946ba in start_thread (arg=0x7fffed75c700) at pthread_create.c:333
#4  0x00007ffff6dc682d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 3 (Thread 0x7fffedf5d700 (LWP 19103)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x0000000000448fd9 in fio_mutex_down (mutex=0x7ffff7fab000) at mutex.c:219
#2  0x00000000004618bd in thread_main (data=<optimised out>) at backend.c:1501
#3  0x00007ffff72946ba in start_thread (arg=0x7fffedf5d700) at pthread_create.c:333
#4  0x00007ffff6dc682d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7fffee75e700 (LWP 19101)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x000000000046f8a4 in helper_thread_main (data=0x7ffff5cb5b90) at helper_thread.c:96
#2  0x00007ffff72946ba in start_thread (arg=0x7fffee75e700) at pthread_create.c:333
#3  0x00007ffff6dc682d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7fe6740 (LWP 19097)):
#0  fio_mutex_up (mutex=0x0) at mutex.c:231
#1  0x0000000000464c8e in run_threads (sk_out=sk_out@entry=0x0) at backend.c:2342
---Type <return> to continue, or q <return> to quit---
#2  0x00000000004650bd in fio_backend (sk_out=sk_out@entry=0x0) at backend.c:2402
#3  0x000000000040d6d8 in main (argc=7, argv=0x7fffffffe5a8, envp=<optimised out>) at fio.c:65
```

When `--max-jobs` is high enough (I've found around 4 on my system) left over fio processes hang around and need killing with -9. On platforms that don't clean up shared memory after process death exiting this way is more painful to recover from.

**Comment by axboe** [comment]
This should fix it:

http://git.kernel.dk/cgit/fio/commit/?id=3bc20ebdf0802db981f9d8b2cb3255c6f4cc9265

**Comment by sitsofe** [comment]
That solved it - thanks Jens!
