### ISSUE TITLE
fio2gnuplot won't generate graphs - 'IOError: [Errno 21] Is a directory: './''

### ISSUE THREAD

**Issue by sammcj** [axboe/fio#56]
- fio-2.1.11
- gnuplot 4.6 patchlevel 6
- Debian 8

Running `# fio2gnuplot -p '*.log' -g` gives:

```
12 files Selected with pattern '*.log'
 |-> s1-san5-128k-md200-randread-para.results_bw.4.log
 |-> s1-san5-128k-md200-randread-para.results_iops.4.log
 |-> s1-san5-128k-md200-randwrite-para.results_bw.3.log
 |-> s1-san5-128k-md200-randwrite-para.results_iops.3.log
 |-> s1-san5-1m-md200-randread-para.results_bw.6.log
 |-> s1-san5-1m-md200-randread-para.results_iops.6.log
 |-> s1-san5-1m-md200-randwrite-para.results_bw.5.log
 |-> s1-san5-1m-md200-randwrite-para.results_iops.5.log
 |-> s1-san5-4k-md200-randread-para.results_bw.2.log
 |-> s1-san5-4k-md200-randread-para.results_iops.2.log
 |-> s1-san5-4k-md200-randwrite-para.results_bw.1.log
 |-> s1-san5-4k-md200-randwrite-para.results_iops.1.log

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pudb/__init__.py", line 77, in runscript
    dbg._runscript(mainpyfile)
  File "/usr/lib/python2.7/dist-packages/pudb/debugger.py", line 371, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "/usr/bin/fio2gnuplot", line 517, in <module>
    sys.exit(main(sys.argv))
  File "/usr/bin/fio2gnuplot", line 497, in main
    compute_aggregated_file(fio_data_file, gnuplot_output_filename, gnuplot_output_dir)
  File "/usr/bin/fio2gnuplot", line 137, in compute_aggregated_file
    f = open(gnuplot_output_dir+gnuplot_output_filename, "w")
IOError: [Errno 21] Is a directory: './'
```

Running a trace, it looks like the variable `gnuplot_output_filename` is empty:

```
file: 's1-san5-4k-md200-randwrite-para.results_iops.1.log'
fio_data_file: list
gnuplot_output_dir: './'
gnuplot_output_filename: ''
temp_files: list
```

Changing the output destination with `-d` or `-o` does not resolve the issue.

If I override `gnuplot_output_dir` to  `gnuplot_output_dir='/tmp/output'` here:
https://github.com/axboe/fio/blob/master/tools/plot/fio2gnuplot#L387

It works - so it looks like somewhere the concatenation of gnuplot_output_dir and gnuplot_output_filename is broken?

**Comment by nbalonso** [comment]
You can loop through the files to get the same outputs `for file in *.log; do fio2gnuplot -p ${file} -g; done`

**Comment by axboe** [comment]
Pulled fix.
