### ISSUE TITLE
sqthread_poll gets stuck for <sq_thread_idle> interval for small IOs on each IO

### ISSUE THREAD

**Issue by edwintorok** [axboe/fio#850]
I was testing `fio-3.16-28-gc656` on  Ubuntu 19.10 and this kernel:
`Linux thunder 5.3.0-19-generic #20-Ubuntu SMP Fri Oct 18 09:04:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

Although reads are working fine writes get stuck.
With iodepth 16 and blocksize 1M it "works" but is very slow as it repeatedly gets stuck for several seconds:
```
sudo fio --ioengine=io_uring --name test --blocksize 1M --size 2G --filename testme --direct=1 --sqthread_poll=1 --rw=write --iodepth=16
test: (g=0): rw=write, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=io_uring, iodepth=16
fio-3.16-28-gc656
Starting 1 process
Jobs: 1 (f=0): [f(1)][100.0%][w=284MiB/s][w=284 IOPS][eta 00m:00s]
test: (groupid=0, jobs=1): err= 0: pid=25875: Sun Oct 27 22:53:55 2019
  write: IOPS=91, BW=91.8MiB/s (96.2MB/s)(2048MiB/22314msec); 0 zone resets
    clat (msec): min=2, max=1012, avg=174.26, stdev=367.82
     lat (msec): min=2, max=1012, avg=174.31, stdev=367.82
    clat percentiles (msec):
     |  1.00th=[    8],  5.00th=[   12], 10.00th=[   12], 20.00th=[   12],
     | 30.00th=[   12], 40.00th=[   12], 50.00th=[   12], 60.00th=[   12],
     | 70.00th=[   12], 80.00th=[   12], 90.00th=[ 1003], 95.00th=[ 1003],
     | 99.00th=[ 1011], 99.50th=[ 1011], 99.90th=[ 1011], 99.95th=[ 1011],
     | 99.99th=[ 1011]
   bw (  KiB/s): min=32768, max=929980, per=100.00%, avg=149791.82, stdev=264412.48, samples=22
   iops        : min=   32, max=  908, avg=146.27, stdev=258.19, samples=22
  lat (msec)   : 4=0.29%, 10=1.46%, 20=81.74%, 50=0.10%, 2000=16.41%
  cpu          : usr=99.96%, sys=0.00%, ctx=2386, majf=0, minf=6
  IO depths    : 1=0.1%, 2=0.1%, 4=0.2%, 8=0.4%, 16=99.3%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,2048,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=91.8MiB/s (96.2MB/s), 91.8MiB/s-91.8MiB/s (96.2MB/s-96.2MB/s), io=2048MiB (2147MB), run=22314-22314msec

Disk stats (read/write):
  nvme0n1: ios=0/1982, merge=0/41, ticks=0/20920, in_queue=15088, util=6.69%
```

Removing `sqthread_poll` it is fast:
``` 
sudo fio --ioengine=io_uring --name test --blocksize 1M --size 2G --filename testme --direct=1 --rw=write --iodepth=16 
test: (g=0): rw=write, bs=(R) 1024KiB-1024KiB, (W) 1024KiB-1024KiB, (T) 1024KiB-1024KiB, ioengine=io_uring, iodepth=16
fio-3.16-28-gc656
Starting 1 process
Jobs: 1 (f=1)
test: (groupid=0, jobs=1): err= 0: pid=25922: Sun Oct 27 22:55:12 2019
  write: IOPS=1381, BW=1382MiB/s (1449MB/s)(2048MiB/1482msec); 0 zone resets
    slat (usec): min=84, max=6755, avg=226.71, stdev=152.99
    clat (usec): min=6357, max=21451, avg=11331.01, stdev=673.76
     lat (usec): min=6485, max=21726, avg=11558.18, stdev=675.59
    clat percentiles (usec):
     |  1.00th=[11076],  5.00th=[11207], 10.00th=[11207], 20.00th=[11207],
     | 30.00th=[11207], 40.00th=[11207], 50.00th=[11338], 60.00th=[11338],
     | 70.00th=[11338], 80.00th=[11338], 90.00th=[11338], 95.00th=[11338],
     | 99.00th=[14353], 99.50th=[16319], 99.90th=[20055], 99.95th=[20841],
     | 99.99th=[21365]
   bw (  MiB/s): min= 1372, max= 1392, per=100.00%, avg=1382.00, stdev=14.14, samples=2
   iops        : min= 1372, max= 1392, avg=1382.00, stdev=14.14, samples=2
  lat (msec)   : 10=0.54%, 20=99.37%, 50=0.10%
  cpu          : usr=12.02%, sys=22.01%, ctx=2056, majf=0, minf=8
  IO depths    : 1=0.1%, 2=0.1%, 4=0.2%, 8=0.4%, 16=99.3%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.1%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,2048,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=1382MiB/s (1449MB/s), 1382MiB/s-1382MiB/s (1449MB/s-1449MB/s), io=2048MiB (2147MB), run=1482-1482msec

Disk stats (read/write):
  nvme0n1: ios=0/2083, merge=0/12, ticks=0/23460, in_queue=16720, util=92.25%
```

Small blocksize is even worse as it seemingly gets stuck forever (during this time moving the mouse is quite laggy too):
```
sudo fio --ioengine=io_uring --name test --blocksize 4k --size 2G --filename testme --direct=1 --sqthread_poll=1 --rw=write --iodepth=16
test: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring, iodepth=16
fio-3.16-28-gc656
Starting 1 process
^Cbs: 1 (f=1): [W(1)][0.1%][w=64KiB/s][w=16 IOPS][eta 09h:35m:50s]
fio: terminating on signal 2

test: (groupid=0, jobs=1): err= 0: pid=25944: Sun Oct 27 22:56:35 2019
  write: IOPS=15, BW=63.0KiB/s (65.5kB/s)(1156KiB/18073msec); 0 zone resets
    clat (usec): min=74, max=1004.5k, avg=1000530.36, stdev=59054.77
     lat (usec): min=76, max=1004.5k, avg=1000531.07, stdev=59054.72
    clat percentiles (msec):
     |  1.00th=[ 1003],  5.00th=[ 1003], 10.00th=[ 1003], 20.00th=[ 1003],
     | 30.00th=[ 1003], 40.00th=[ 1003], 50.00th=[ 1003], 60.00th=[ 1003],
     | 70.00th=[ 1003], 80.00th=[ 1003], 90.00th=[ 1003], 95.00th=[ 1003],
     | 99.00th=[ 1003], 99.50th=[ 1003], 99.90th=[ 1003], 99.95th=[ 1003],
     | 99.99th=[ 1003]
   bw (  KiB/s): min=  128, max=  136, per=100.00%, avg=128.47, stdev= 1.94, samples=17
   iops        : min=   32, max=   34, avg=32.12, stdev= 0.49, samples=17
  lat (usec)   : 100=0.35%
  lat (msec)   : 2000=99.65%
  cpu          : usr=99.96%, sys=0.00%, ctx=1858, majf=0, minf=7
  IO depths    : 1=0.3%, 2=0.7%, 4=1.4%, 8=2.8%, 16=94.8%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=99.6%, 8=0.0%, 16=0.4%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,289,0,0 short=0,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=16

Run status group 0 (all jobs):
  WRITE: bw=63.0KiB/s (65.5kB/s), 63.0KiB/s-63.0KiB/s (65.5kB/s-65.5kB/s), io=1156KiB (1184kB), run=18073-18073msec

Disk stats (read/write):
  nvme0n1: ios=0/138, merge=0/258, ticks=0/454, in_queue=288, util=0.96%
```

Interestingly running the command under `perf record -g -F 99` it seems to get stuck less, but with `perf record -g` it does.

Stacktrace when stuck looks like:
```
0x000055c6f2caf153 in fio_ioring_getevents (td=0x7f4f5abf0000, min=1, max=1, t=<optimised out>) at engines/io_uring.c:275
275		} while (events < min);
(gdb) bt
#0  0x000055c6f2caf153 in fio_ioring_getevents (td=0x7f4f5abf0000, min=1, max=1, t=<optimised out>) at engines/io_uring.c:275
#1  0x000055c6f2c3f886 in td_io_getevents (td=td@entry=0x7f4f5abf0000, min=1, max=1, t=0x0) at ioengines.c:263
#2  0x000055c6f2c68697 in io_u_queued_complete (td=td@entry=0x7f4f5abf0000, min_evts=<optimised out>, min_evts@entry=1) at io_u.c:2061
#3  0x000055c6f2c8cf17 in wait_for_completions (time=0x7ffea9cfc800, td=0x7f4f5abf0000) at backend.c:448
#4  do_io (bytes_done=0x7ffea9cfc830, td=0x7f4f5abf0000) at backend.c:1083
#5  thread_main (data=data@entry=0x55c6f44f0170) at backend.c:1791
#6  0x000055c6f2c8f106 in run_threads (sk_out=sk_out@entry=0x0) at backend.c:2368
#7  0x000055c6f2c8f208 in fio_backend (sk_out=0x0) at backend.c:2504
#8  0x000055c6f2c2f5ab in main (argc=14, argv=0x7ffea9d04c48, envp=<optimised out>) at fio.c:60
```

It appears that there is a 1s delay between each `getevents` (FWIW the kernel thread is running 100% during this time):
```
sudo fio --ioengine=io_uring --name test --blocksize 4k --size 2G --filename testme --direct=1 --sqthread_poll=1 --rw=write --iodepth=1 --debug=io 2>&1 | ts -s %.s
0.379221 fio: set debug option io
0.379334 test: (g=0): rw=write, bs=(R) 4096B-4096B, (W) 4096B-4096B, (T) 4096B-4096B, ioengine=io_uring, iodepth=1
0.379351 fio-3.16-28-gc656
0.379371 Starting 1 process
0.496124 io       27600 declare unneeded cache testme: 0/2147483648
0.496252 io       27600 fill: io_u 0x55a71e20ef40: off=0x0,len=0x1000,ddir=1,file=testme
0.496309 io       27600 prep: io_u 0x55a71e20ef40: off=0x0,len=0x1000,ddir=1,file=testme
0.496362 io       27600 prep: io_u 0x55a71e20ef40: ret=0
0.496412 io       27600 queue: io_u 0x55a71e20ef40: off=0x0,len=0x1000,ddir=1,file=testme
0.496463 io       27600 calling ->commit(), depth 1
0.496525 io       27600 io_u_queued_complete: min=1
1.499897 io       27600 getevents: 1
1.500008 io       27600 complete: io_u 0x55a71e20ef40: off=0x0,len=0x1000,ddir=1,file=testme
1.500066 io       27600 fill: io_u 0x55a71e20ef40: off=0x1000,len=0x1000,ddir=1,file=testme
1.500119 io       27600 prep: io_u 0x55a71e20ef40: off=0x1000,len=0x1000,ddir=1,file=testme
1.500174 io       27600 prep: io_u 0x55a71e20ef40: ret=0
1.500229 io       27600 queue: io_u 0x55a71e20ef40: off=0x1000,len=0x1000,ddir=1,file=testme
1.500280 io       27600 calling ->commit(), depth 1
1.500335 io       27600 io_u_queued_complete: min=1
2.503892 io       27600 getevents: 1
2.504009 io       27600 complete: io_u 0x55a71e20ef40: off=0x1000,len=0x1000,ddir=1,file=testme
2.504076 io       27600 fill: io_u 0x55a71e20ef40: off=0x2000,len=0x1000,ddir=1,file=testme
2.504137 io       27600 prep: io_u 0x55a71e20ef40: off=0x2000,len=0x1000,ddir=1,file=testme
2.504199 io       27600 prep: io_u 0x55a71e20ef40: ret=0
2.504256 io       27600 queue: io_u 0x55a71e20ef40: off=0x2000,len=0x1000,ddir=1,file=testme
2.504306 io       27600 calling ->commit(), depth 1
2.504358 io       27600 io_u_queued_complete: min=1
3.507886 io       27600 getevents: 1
3.507987 io       27600 complete: io_u 0x55a71e20ef40: off=0x2000,len=0x1000,ddir=1,file=testme
3.508042 io       27600 fill: io_u 0x55a71e20ef40: off=0x3000,len=0x1000,ddir=1,file=testme
3.508106 io       27600 prep: io_u 0x55a71e20ef40: off=0x3000,len=0x1000,ddir=1,file=testme
3.508167 io       27600 prep: io_u 0x55a71e20ef40: ret=0
3.508217 io       27600 queue: io_u 0x55a71e20ef40: off=0x3000,len=0x1000,ddir=1,file=testme
3.508267 io       27600 calling ->commit(), depth 1
3.508316 io       27600 io_u_queued_complete: min=1
4.511882 io       27600 getevents: 1
4.511967 io       27600 complete: io_u 0x55a71e20ef40: off=0x3000,len=0x1000,ddir=1,file=testme
4.512027 io       27600 fill: io_u 0x55a71e20ef40: off=0x4000,len=0x1000,ddir=1,file=testme
4.512079 io       27600 prep: io_u 0x55a71e20ef40: off=0x4000,len=0x1000,ddir=1,file=testme
4.512133 io       27600 prep: io_u 0x55a71e20ef40: ret=0
4.512190 io       27600 queue: io_u 0x55a71e20ef40: off=0x4000,len=0x1000,ddir=1,file=testme
4.512247 io       27600 calling ->commit(), depth 1
4.512298 io       27600 io_u_queued_complete: min=1
5.515881 io       27600 getevents: 1
5.515964 io       27600 complete: io_u 0x55a71e20ef40: off=0x4000,len=0x1000,ddir=1,file=testme
5.516024 io       27600 fill: io_u 0x55a71e20ef40: off=0x5000,len=0x1000,ddir=1,file=testme
5.516075 io       27600 prep: io_u 0x55a71e20ef40: off=0x5000,len=0x1000,ddir=1,file=testme
5.516136 io       27600 prep: io_u 0x55a71e20ef40: ret=0
5.516186 io       27600 queue: io_u 0x55a71e20ef40: off=0x5000,len=0x1000,ddir=1,file=testme
5.516237 io       27600 calling ->commit(), depth 1
5.516274 io       27600 io_u_queued_complete: min=1
6.519895 io       27600 getevents: 1
6.520010 io       27600 complete: io_u 0x55a71e20ef40: off=0x5000,len=0x1000,ddir=1,file=testme
6.520064 io       27600 fill: io_u 0x55a71e20ef40: off=0x6000,len=0x1000,ddir=1,file=testme
6.520117 io       27600 prep: io_u 0x55a71e20ef40: off=0x6000,len=0x1000,ddir=1,file=testme
6.520164 io       27600 prep: io_u 0x55a71e20ef40: ret=0
6.520214 io       27600 queue: io_u 0x55a71e20ef40: off=0x6000,len=0x1000,ddir=1,file=testme
6.520267 io       27600 calling ->commit(), depth 1
6.520312 io       27600 io_u_queued_complete: min=1
7.523885 io       27600 getevents: 1
7.524019 io       27600 complete: io_u 0x55a71e20ef40: off=0x6000,len=0x1000,ddir=1,file=testme
7.524075 io       27600 fill: io_u 0x55a71e20ef40: off=0x7000,len=0x1000,ddir=1,file=testme
7.524134 io       27600 prep: io_u 0x55a71e20ef40: off=0x7000,len=0x1000,ddir=1,file=testme
7.524180 io       27600 prep: io_u 0x55a71e20ef40: ret=0
7.524227 io       27600 queue: io_u 0x55a71e20ef40: off=0x7000,len=0x1000,ddir=1,file=testme
7.524272 io       27600 calling ->commit(), depth 1
7.524310 io       27600 io_u_queued_complete: min=1
```

That 1s looks too much like the 1s timeout in the kernel thread when polling, I don't think it is a coincidence. 
If I set the timeout to 10s then the delays become 10s each time (and makes the whole system painful to use (I got 8 cores, yet 2 fully utilized cores can freeze activity within Xorg quite visibly: when I am inside gdb typing `c` and pressing enter freezes the terminal until I press ^C again, I don't see `Continuing` displayed immediately):
```
+        p.sq_thread_idle = 10000;
```

Can you reproduce this?

**Comment by edwintorok** [comment]
I've tested some upstream kernels and they work without the problems described above, so Ubuntu must be a bit behind:
```
Linux thunder 5.4.0-050400rc5-generic #201910271430 SMP Sun Oct 27 18:33:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
Linux thunder 5.3.7-050307-generic #201910180652 SMP Fri Oct 18 10:56:47 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
